### ISSUE TITLE
Establish a mechanism for where MarFS configuration file is

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#10]
Right now I have the API user pass the path to the configuration file. I propose to change this so that the API clients don't have to implement the same mechanism multiple times. I propose that MarFS configuration search for the configuration file in this order:

1) Value of the MARFSCONFIGRC environment variable.

2) $HOME/.marfsconfigrc file.

3) /etc/marfsconfigrc file.

If none of those is found, the read_configuration fails.

**Comment by jti-lanl** [comment]
Good idea.  Thanks.

**Comment by brettkettering** [comment]
I have implemented this in marfs_configuration.[h,c], but it is not yet checked-in. I'm waiting on a solution to Namespaces' repo_range_lists from the configuration parser.

**Comment by brettkettering** [comment]
It's all updated and working with how the base configuration parser works at this time. It's all checked-in. I also removed the redundant marfs_, namespace_, and repo_ prefixes to marfs_configuration.h struct members.
