### ISSUE TITLE
Optimize PVFS/OrangeFS for zero-byte file creation

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#100]
Currently when zero-byte files are created using PVFS/OrangeFS there are 64 parts created that are all empty. This incurs a performance overhead that really is not needed. See if you can find the place in the code where this happens and remove it. We only want the metadata entry to be created, but don't want a bunch of empty data parts created when there is no data. This will give us a better idea of PVFS/OrangeFS's performance in creating large numbers of files under MarFS.

**Comment by hbchen** [comment]
Those 64 subdirs are Orangefs's internal data structure.  I don't think that we want to change it.

It requires a big software change inside  the Orangefs file system.

If you really want to change it you may call the new one "Orangefs-NG" (Orangefs next generation).


HB



________________________________

**Comment by boydwilson** [comment]
I noticed this and wanted to mention that the 64 subdirectories are created when you create the storage areas.  If file stuffing is turned on, which is the default, then only one datafile is created, and the physical data file may not get created until data is written to it.

**Comment by brettkettering** [comment]
HB verified that disabling fileStuffing eliminates the data store creation of the 64 sub-directories for zero-byte files and speeds-up file creation. There is no need to optimize PVFS/OrangeFS.
