### ISSUE TITLE
Tag the repo for the Open Science release(s)

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#103]
It would be nice to keep track of exactly which commits of the repo are running for Open Science.  We should put a tag on that commit.

I suspect we opened to OS users with 97c6f0f
And maybe we have now moved up to a440d0d
[We can find this out.]

Alfred suggested that we use a tag that is less than 1.0 (e.g. 0.1.0), saving 1.0 for the release later this year.  That makes sense, but we should also consider aligning the version tag with our marfs format-version (currently 1.0), which goes into object-IDs, etc.  (Discussion in issue #35.)

**Comment by brettkettering** [comment]
Jeff:

We are past this time. Is this still something you want to do? If not, shall we close this?

Brett

**Comment by jti-lanl** [comment]
I'm not sure we'll ever care to recreate the state of affairs at the end of the OS test period, but it seems like something we should be able to do.  I tagged both pftool (cpp branch) and marfs with "OS.2", on the commit versions that I see in /opt/campaign on the master.
