### ISSUE TITLE
Figure out if it's possible to run OrangeFS strictly in user space

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#107]
We need to be able to run OrangeFS servers and clients on HPC system compute nodes without needing to be root or needing to have files in root-owned space be edited. That is, we cannot rely on having to edit or place files in /etc, /lib, /bin, /sbin, /opt, etc.

Talk to David Bonnie (formerly worked on OrangeFS) or Boyd Wilson. Find out if it's possible to run the client and server without ever needing root intervention.

**Comment by boydwilson** [comment]
The only item that needs root is the Kernel Module (and mounting with it).  You can use MPI, userint, API all in user space.    The conf file can be referenced on the command line, if you have the needed libs in the LD_LIBRARY_PATH and you could have the log files go anywhere including /tmp.

**Comment by brettkettering** [comment]
Boyd:

Thanks for responding. Something seems to be wrong with the PVFS2 Users List right now.

If the only thing that requires root is loading the Kernel module and mounting a file system, can we use OrangeFS without loading the kernel module and mounting a file system? I see on the OrangeFS page here, https://www.orangefs.org/documentation/releases/current/doc/pvfs2-guide/pvfs2-guide.php, that what you say is true. What I can't find is if it is necessary to load the Kernel module and mount a file system.

For example, PLFS did not require any root privileges or mounts to use it through the user space API.

We need to run completely in user space and we cannot even ask the Admins to load the module and mount a file system for us.

We want to use OrangeFS as a metadata file system for MarFS and we need that use to be completely through some API that does not require root to do anything.

Thanks,
Brett

**Comment by thewacokid** [comment]
http://www.orangefs.org/documentation/releases/current/doc/pvfs2-quickstart/pvfs2-quickstart.php#SECTION00043000000000000000

You only need the kernel module for accessing the OrangeFS filesystem via existing POSIX-y tools.  Unless something has changed, you should be able to configure your environment to allow use of the MPI-IO / native API access without any local "mountpoint", just a reference in the pvfs2tab file.

**Comment by hbchen** [comment]
?David,

I tried.

It works now.

Thanks.


HB



________________________________

**Comment by brettkettering** [comment]
HB came in and said he figured out how to configure it without any file in root space and without having to load a kernel module. Just using the PVFS lib API. Closing this issue.

**Comment by boydwilson** [comment]
glad you got it working, we will check into the users list.

**Comment by jdburton** [comment]
There is also a fuse module, which will allow you to mount the filesystem in userspace, if you need to. Performance and functionality of the fuse module, however, is not as good as the kernel module, native API, or MPI-IO interfaces.
