### ISSUE TITLE
Implement OrangeFS instantiation of MDAL

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#108]
Jeff Inman is working on a virtual class for metadata handling in MarFS. We will need a specific instantiation for OrangeFS in the Program Development effort to show remarkable levels of metadata speed through zero-byte file creation.

**Comment by jti-lanl** [comment]
I've got some commits pending.   Wait for those, to get a correct picture of the interface.

**Comment by jti-lanl** [comment]
MDAL support for this task is now in place (as of aafa604).

**Comment by brettkettering** [comment]
Decided to take a different direction on this and no longer need this instantiation.
