### ISSUE TITLE
Make open/write defer opening an object-stream (PUT), like open/read does (with GET)

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#112]
This was item "(3)" in issue #83.  Moving here, so we can close that.

This comes up for the MD scaling demo.  Otherwise, we don't particularly care about zero-length files.

Refactor MarFS write() to work like read()
-- don't start the PUT in open(), wait until the write().
-- zero-length files might have no object? (Maybe that's good.)
-- tweak code to handle zero-length files?

The point of this is to make it easier/cheaper to write zero-length files. Currently, we'd pay the cost of opening/closing a PUT for each zero-length file.

**But**, zero-length files invite questions, which I've recorded in item #111.

**Comment by jti-lanl** [comment]
The suggestion in #111 to use a DIRECT repo, for size=0, would make this problem go away (?)

**Comment by brettkettering** [comment]
Related to #96.

**Comment by brettkettering** [comment]
A good candidate for the DAL (Data Abstraction Layer) work.

**Comment by wfvining** [comment]
Jeff and I decided we should do this in MarFS itself, rather than leaving it to the various DAL implementations. I have a working implementation in the `lazy-open` branch which needs further integration testing against both the OBJ and MC DALs, but should be just about ready to merge.

**Comment by wfvining** [comment]
This has been done as part of implementing marfs_flush().
