### ISSUE TITLE
Test Open Science Campaign Storage performance w/o Scality logging

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#114]
After Ron turns-off RING server logging for the Open Science Campaign Storage, test the performance and see if it returns to previously seen levels or better.

**Comment by gransom** [comment]
This is a very old issue which most likely was simply never closed.  Open Sci Campaign testing was completed some time ago.  This issue also refers to testing with parameters that are no longer relevant.
Closing.
