### ISSUE TITLE
'cp' from sparse-file to fuse fails

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#122]
The problem is that the kernel invokes fuse-ftruncate with the size of the sparse file (i.e. to create a sparse file on the destination), and we don't allow ftruncate to non-zero.  If there were some way for fuse to determine that this is what is going on, we could allow the op to appear to succeed.

**Comment by thewacokid** [comment]
Just as a note, this is reproducible with any file that has large holes in it.  Specifying "--sparse=never" for cp fixes it entirely, as it turns off the auto-hole-finding logic in cp.

**Comment by thewacokid** [comment]
Working as intended.
