### ISSUE TITLE
cp into MarFS with odd permissions (fails for read-only files, mangles write permissions on others)

### ISSUE THREAD

**Issue by thewacokid** [mar-file-system/marfs#134]
[I added some line-breaks, so the markup formatting would be more legible to me.  I hope you don't mind. -- jti]

I'm not sure why, but here's what we see behavior-wise:

* LOCAL FS TO MARFS *

-bash-4.1$ ls -alh
total 24K
drwxr-xr-x 2 dbonnie dbonnie 160 May 24 08:47 .
drwxrwxrwt 8 root    root    240 May 24 08:48 ..
-r-------- 1 dbonnie dbonnie  15 May 24 08:46 file1
-rw------- 1 dbonnie dbonnie  16 May 24 08:47 file2
-rw-r----- 1 dbonnie dbonnie  28 May 24 08:47 file3
-rw-rw---- 1 dbonnie dbonnie  34 May 24 08:47 file4
-rw-rw-r-- 1 dbonnie dbonnie  27 May 24 08:47 file5
-rw-rw-rw- 1 dbonnie dbonnie   7 May 24 08:47 file6

-bash-4.1$ cp * /campaign/admins/dbonnie/
cp: cannot create regular file `/campaign/admins/dbonnie/file1': Permission denied

-bash-4.1$ ls -alh /campaign/admins/dbonnie/
total 0
drwxr-xr-x 2 dbonnie dbonnie 4.0K May 24 08:48 .
drwxr-xr-x 8 root    root    4.0K May 24 08:45 ..
-r-------- 1 dbonnie dbonnie    0 May 24 08:48 file1
-rw------- 1 dbonnie dbonnie   16 May 24 08:48 file2
-rw-r----- 1 dbonnie dbonnie   28 May 24 08:48 file3
-rw-r----- 1 dbonnie dbonnie   34 May 24 08:48 file4
-rw-r--r-- 1 dbonnie dbonnie   27 May 24 08:48 file5
-rw-r--r-- 1 dbonnie dbonnie    7 May 24 08:48 file6

-bash-4.1$ cp -p * /campaign/admins/dbonnie/
cp: cannot create regular file `/campaign/admins/dbonnie/file1': Permission denied

-bash-4.1$ ls -alh /campaign/admins/dbonnie/
total 0
drwxr-xr-x 2 dbonnie dbonnie 4.0K May 24 08:49 .
drwxr-xr-x 8 root    root    4.0K May 24 08:45 ..
-r-------- 1 dbonnie dbonnie    0 May 24 08:49 file1
-rw------- 1 dbonnie dbonnie   16 May 24 08:49 file2
-rw-r----- 1 dbonnie dbonnie   28 May 24 08:49 file3
-rw-rw---- 1 dbonnie dbonnie   34 May 24 08:49 file4
-rw-rw-r-- 1 dbonnie dbonnie   27 May 24 08:49 file5
-rw-rw-rw- 1 dbonnie dbonnie    7 May 24 08:49 file6

* NOT MARFS DEST, NFS MOUNT *

-bash-4.1$ mkdir /users/dbonnie/test_copy

-bash-4.1$ cp * /users/dbonnie/test_copy/

-bash-4.1$ ls -alh /users/dbonnie/test_copy/
total 12K
drwxrwxr-x  2 dbonnie dbonnie 4.0K May 24 08:45 .
drwxr-x--x 28 dbonnie users   8.0K May 24 08:45 ..
-r--------  1 dbonnie dbonnie   15 May 24 08:45 file1
-rw-------  1 dbonnie dbonnie   16 May 24 08:45 file2
-rw-r-----  1 dbonnie dbonnie   28 May 24 08:45 file3
-rw-rw----  1 dbonnie dbonnie   34 May 24 08:45 file4
-rw-rw-r--  1 dbonnie dbonnie   27 May 24 08:45 file5
-rw-rw-r--  1 dbonnie dbonnie    7 May 24 08:45 file6

-bash-4.1$ cp -p * /users/dbonnie/test_copy/
cp: cannot create regular file `/users/dbonnie/test_copy/file1': Permission denied

-bash-4.1$ ls -alh /users/dbonnie/test_copy/
total 12K
drwxrwxr-x  2 dbonnie dbonnie 4.0K May 24 08:45 .
drwxr-x--x 28 dbonnie users   8.0K May 24 08:45 ..
-r--------  1 dbonnie dbonnie   15 May 24 08:45 file1
-rw-------  1 dbonnie dbonnie   16 May 24 08:47 file2
-rw-r-----  1 dbonnie dbonnie   28 May 24 08:47 file3
-rw-rw----  1 dbonnie dbonnie   34 May 24 08:47 file4
-rw-rw-r--  1 dbonnie dbonnie   27 May 24 08:47 file5
-rw-rw-rw-  1 dbonnie dbonnie    7 May 24 08:47 file6

So "cp -p" seems correct, minus the error writing the read-only files.  I'm not sure why regular "cp" results in different results for group write permissions (perhaps umask related?).

**Comment by jti-lanl** [comment]
It looks like we have some issues creating read-only files:

* Apparently, it's a POSIX error to set xattrs on a read-only file (?)

Note that the size of file1 is 0, after the copy to the marfs destination.  I presume that the kernel calls fuse `mknod` with the read-only mode that it wants the file to have.  The error you see comes from us trying to install marfs xattrs.

> $ touch  ~jti/test/ro                                                                                                                                                                                                                          
> $ touch  ~jti/test/rw
> $ chmod ugo-w  ~jti/test/ro                                                                                                                                                                                                                    
> $ ls -l  ~jti/test/
> total 0
> -r--r--r--. 1 jti jti 0 May 24 10:10 ro
> -rw-rw-r--. 1 jti jti 0 May 24 10:10 rw
> 
> $ attr -s foo -V 1 ~jti/test/rw
> Attribute "foo" set to a 1 byte value for /home/jti/test/rw:
> 1
> 
> $ attr -s foo -V 1 ~jti/test/ro
> attr_set: Permission denied
> Could not set "foo" for /home/jti/test/ro

**Possible solution**: We could stash the desired final mode in the file-handle, add user-write access, and install the final mode in release.  But: we don't always know that mknod is being called in service of open.  Maybe we really have to do this stash-mode/add-user-writable/install-final-mode dance in mknod, and then again in open/close?

* For the group-write-permissions thing (in the marfs fuse cp example), notice that the destination-directory lacks group-writability.  I didn't know this before your example, but, sure enough, if I copy a file that includes 0022 permission-bits into a directory without g/o write-access, those bits get stripped off the file:

> $ mkdir /dev/shm/jti/no_grp_w
> $ ls -ld /dev/shm/jti/no_grp_w
> drwxr-xr-x. 2 root root 40 May 24 09:51 /dev/shm/jti/no_grp_w
> 
> $ chmod go+w foo
> $ ls -l foo
> -rw-rw-rw-. 1 root root 3 May 24 09:58 foo
> 
> $ cp foo /dev/shm/jti/no_grp_w
> $ ls -l /dev/shm/jti/no_grp_w/foo 
> -rw-r--r--. 1 root root 3 May 24 09:58 /dev/shm/jti/no_grp_w/foo

**Comment by jti-lanl** [comment]
Fixed.
