### ISSUE TITLE
fuse crashes when user tries to list root directory

### ISSUE THREAD

**Issue by cadejager** [mar-file-system/marfs#14]
To reproduce login as a user and ls /marfs

The only solution I have found is to remount marfs.

**Comment by jti-lanl** [comment]
Thanks.  this turned up several bugs.  fuse-functions were using an unsigned value to capture marfs_ops return-codes, then checking for < 0.  marfs_opendir() was also freeing dh on a access-violation (which this is), but fuse_opendir() was also freeing it.

All fixed, but not yet committed.  (Maybe I'll pull this out of the ongoing changes, and commit it in isolation.)
