### ISSUE TITLE
NFS exports can put the FUSE daemon into a broken state

### ISSUE THREAD

**Issue by thewacokid** [mar-file-system/marfs#142]
Transport Endpoint Disconnected when trying to access the filesystem in this state.

Reproducer:

NFS export of the FUSE mount using 64 nfsd threads (yes, this is intentionally bad).  FUSE can be mounted with either direct_io or without, both seemed to trigger this.

Then, on a client, simply read from a large file (~1 GB) or two using dd, block size of 1 MB (not sure if this is significant, but it's what I was doing that exposed it).

After a few seconds of running, the FUSE daemon will disconnect with the transport endpoint error.  I didn't dig into why, but it may provide some insight into thread safety.

**Comment by jti-lanl** [comment]
In my experience, Transport Disconnected means the fuse daemon crashed.  So, clearly a bug.

However, it's known that NFS has expectations for what an underlying filesystem can do (or do efficiently) which are not MarFS specialties.  Specifically, NFS expects different threads to be able to read at more-or-less arbitrary offsets through the same file-handle (something we've tried to mitigate, but with which we're still struggling), and also to scatter arbitrary reads across multiple file-handles (a lot harder to mitigate).

We've optimized MarFS for streaming sequential reads and writes, with parallel streams able to operate on individual (complete) chunks.  With an underlying object-store, we should be able to support the arrogant assumptions of NFS correctly, but for various reasons it is likely to be very (very) inefficient, in the current incarnation.  I think planned future work might allow this to become more efficient.

Nevertheless, crashing is not correct behavior.  Thanks for a good test-case.

**Comment by thewacokid** [comment]
I'm unsure which commit fixed this, but this doesn't appear to be reproducible on current builds.

**Comment by jti-lanl** [comment]
Perhaps it was fixed by just using a newer version of NFS?

If so, the problem may still exist for older versions of NFS.


On Aug 22, 2019, at 1:24 PM, David Bonnie <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm unsure which commit fixed this, but this doesn't appear to be reproducible on current builds.
