### ISSUE TITLE
MarFS xattr inconsistencies

### ISSUE THREAD

**Issue by cphoffma** [mar-file-system/marfs#15]
There are inconsistencies between what the MarFS documentation says for marfs_objid and marfs_post xattrs versus what is actually being written in marfs code.

We should verify that marfs writes according to the MarFS Documentation and that:
-All fields are included
-All fields are in the correct order

**Comment by brettkettering** [comment]
The design document, on page 16, says that the xattr documentation needs to be updated. On page 17 it specifically says to update the documentation for MAR_objid. Let's make the document and what's done and correct in the code consistent. If you want, send me the list of xattrs and what's in each and I'll update the document.

**Comment by brettkettering** [comment]
The content of the xattrs in the code is working and we believe this is correct. Brett I'll update the document to match what's in the code. Can look at xattrs and see what's there and document that.

**Comment by brettkettering** [comment]
I updated the document to match what the code does with MarFS_objid and MarFS_post xattrs.
