### ISSUE TITLE
build with autotools

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#151]
The Makefile-approach was nice, early on, when we needed flexibility and a convenient repository for techniques.  We're past that, now.  We can keep some of the makefile conveniences.

**Comment by wfvining** [comment]
The autotools build is complete. It will be rolled in to master with multi-component storage (74fe7194). However, before we merge I would like to look in to making asw4c, PA2X, and erasureUtils _actual_ submodules.

Below is a summary of the changes so far.

## Overview of Changes

* libconfig is no longer a separate entity. It is rolled in to libmarfs, so any applications that need the marfs config now just need to link libmarfs. I have submitted a pull request to PFTool that addresses this change.
* The location where libmarfs.a, marfs_fuse, and all the utilities are built is now the root of the source tree. (not fuse/src and the individual utility folders).
* To simplify the build and make it easier to add non gpfs-specific utilities later I have restructured the utilities subtree.
* If you use `make mnt` to mount marfs you will need to provide the variable `MARFS_MNT=/mount.point` to the configure script (or set it in your environment).

## Example usage
```
$ cd marfs
$ autoreconf --install
$ ./configure --enable-mc --enable-logging=stdout LDFLAGS="-L/path/to/libne" MARFS_MNT=/campaign
...
$ make
$ sudo make mnt MARFSCONFIGRC=$MARFSCONFIGRC
```

**Comment by wfvining** [comment]
This is completed and merged in to the master branch.
