### ISSUE TITLE
DAL needs delete

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#158]
All MarFS deletes currently just push marfs files into the trash.  Eventually, GC needs to be able to delete the underlying storage.  To make this generic, GC wants to go through the DAL.

This is awkward, because currently all DAL ops have context associated with maintaining a stream, whereas DEL is just given an object-ID.  It's a little awkward to fit into object_stream.c for the same reason.  But it can be done.  Basically, we're going all the way back to aws4c calls, adapting s3_delete().

If a DAL context is needed, we should provide a slightly-higher-level function, eg. delete_data(), to do whatever is needed to start from a  MarFS_FileHandle and do the delete.  Probably just DAL init, delete, destroy.  That would keep GC simple.

I'm starting some tentative work in the "gc-dal" branch.  Alfred will also work there, with corresponding changes to GC.

**Comment by jti-lanl** [comment]
Fixed in the "gc-del" branch, pending more-extensive testing by @atorrez.

**Comment by atorrez** [comment]
Testing complete with no issues.  Branch merged with gc-dal and pushed to master.
