### ISSUE TITLE
object recovery-info is still just fake data

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#16]
We install recovery-info into all objects, and are forced to do arithmetic to manage writing this info into object streams with a given content-length (i.e. to include user-data plus recovery-info), but the info itself is still just fake, intended to support debugging.

**Comment by brettkettering** [comment]
This is a necessary feature for the Open Science MarFS version. I thought we had recovery information added to the objects. What's holding us up from making it what it is documented to be?

**Comment by brettkettering** [comment]
FUSE, PFTool, and the Packer all need to put the same recovery information in files.

**Comment by jti-lanl** [comment]
Fixed.

One option for the packer is simply to copy the data-portions of the (small) input objects into the output object, while buffering up the recovery-info portions of those input objects.  When the size of the accumulated data-portions, plus the size of the accumulated rec-info-portions, plus MARFS_REC_TAIL_SIZE does not leave room for the next data-portion, then write all the buffered rec-info, write the "tail", and close the object.  Then open a new packed-object, reset the counters to start packing the new object, write that data-portion into the new object, buffer that rev-info-portion, and away you go ...
