### ISSUE TITLE
Quotas initially reports incorrect trash file count

### ISSUE THREAD

**Issue by wfvining** [mar-file-system/marfs#164]
While investigating issue #163 I have found that `marfs_quota` initially reports an incorrect trash file count. The following commands will reproduce the issue.

```bash
for i in `seq 0 1999`
do
    echo "small uni number $i" >/marfs/ns/d2/wfv.uni.0.$i
done
```

Running quotas before and after the snippet above shows the number of files increase by 2000 as expected (the original uni count is 8650). 
```
[ns]
total_file_count:    13349
total_size:          1056996846293 (984G)
uni count:           10650
multi count:         17
packed count:        2682
restart_file_count:  7265
restart_size:        16704
trash_file_count:    0
trash_size:          0
```
After deleting the files:
```
$ rm -rf /marfs/ns/d2
```
quotas shows the the number of trash files increase from 0 to some number less than 2000, and total file count decrease by the same amount. 
```
[ns]
total_file_count:    12018
total_size:          1056996813742 (984G)
uni count:           9319
multi count:         17
packed count:        2682
restart_file_count:  7265
restart_size:        16704
trash_file_count:    1306
trash_size:          31921
```
Checking the trash directly reveals that all files I expect to be there are present:
```
$ find /path/to/trash -name wfv.uni.0.* -print | wc -l
4000
```
Finally, running quotas again gives the correct trash file count.
```
[ns]
total_file_count:    11349
total_size:          1056996797403 (984G)
uni count:           8650
multi count:         17
packed count:        2682
restart_file_count:  7265
restart_size:        16704
trash_file_count:    2000
trash_size:          48890
```

**Comment by thewacokid** [comment]
Remember there is a lag on the shadow inode table. Changes to the filesystem are not immediately visible.‎ It may be some number of minutes before you see changes in the policy engine output.

Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.
From: Will Vining
Sent: Friday, September 16, 2016 2:51 PM
To: mar-file-system/marfs
Reply To: mar-file-system/marfs
Subject: [mar-file-system/marfs] Quotas initially reports incorrect trash file count (#164)



While investigating issue #163<https://github.com/mar-file-system/marfs/issues/163> I have found that marfs_quota initially reports an incorrect trash file count. The following commands will reproduce the issue.

for i in `seq 0 1999`
do
    echo "small uni number $i" >/marfs/ns/d2/wfv.uni.0.$i
done

Running quotas before and after the snippet above shows the number of files increase by 2000 as expected (the original uni count is 8650).

[ns]
total_file_count:    13349
total_size:          1056996846293 (984G)
uni count:           10650
multi count:         17
packed count:        2682
restart_file_count:  7265
restart_size:        16704
trash_file_count:    0
trash_size:          0


After deleting the files:

$ rm -rf /marfs/ns/d2


quotas shows the the number of trash files increase from 0 to some number less than 2000, and total file count decrease by the same amount.

[ns]
total_file_count:    12018
total_size:          1056996813742 (984G)
uni count:           9319
multi count:         17
packed count:        2682
restart_file_count:  7265
restart_size:        16704
trash_file_count:    1306
trash_size:          31921


Checking the trash directly reveals that all files I expect to be there are present:

$ find /path/to/trash -name wfv.uni.0.* -print | wc -l
4000


Finally, running quotas again gives the correct trash file count.

[ns]
total_file_count:    11349
total_size:          1056996797403 (984G)
uni count:           8650
multi count:         17
packed count:        2682
restart_file_count:  7265
restart_size:        16704
trash_file_count:    2000
trash_size:          48890

**Comment by wfvining** [comment]
Okay, perhaps I jumped the gun on posting this then. I wanted to document what was going on just in case. I will go ahead and close this.
