### ISSUE TITLE
Copying a file into fuse does not preserve timestamps

### ISSUE THREAD

**Issue by wfvining** [mar-file-system/marfs#174]
If `cp` is invoked with `--preserve=timestamps` the destination file should have the same mtime as the source. When copying in to fuse, however, the mtime does not match mtime on the source.

```
$ cp --preserve=timestamps ~/foo /marfs/wfvining/foo
$ stat ~/foo
  File: `~/foo'
  Size: 805306368       Blocks: 1572872    IO Block: 32768  regular file
Device: 12h/18d Inode: 15529035    Links: 1
Access: (0664/-rw-rw-r--)  Uid: (23774/wfvining)   Gid: (23774/wfvining)
Access: 2017-01-11 13:02:46.734006438 -0700
Modify: 2016-12-02 13:22:30.522748908 -0700
Change: 2017-01-12 07:07:15.924111809 -0700
$ stat /marfs/wfvining/foo
  File: `/marfs/wfvining/foo'
  Size: 805306368       Blocks: 0          IO Block: 262144 regular file
Device: 24h/36d Inode: 756835      Links: 1
Access: (0644/-rw-r--r--)  Uid: (23774/wfvining)   Gid: (23774/wfvining)
Access: 2017-01-11 13:02:46.734006438 -0700
Modify: 2017-01-12 07:08:20.633718000 -0700
Change: 2017-01-12 07:08:20.635344000 -0700
```

It appears to just be the timestamps that are not correct, with `--preserve=mode` the mode on the destination file is preserved.

**Comment by wfvining** [comment]
This is not an easy fix. `cp` calls `utimens` before calling close, which means that when we truncate the MD file and update it's xattrs in `marfs_release()` we will overwrite the changes cp made to the timestamps. The simplest solution I can think of is to force `marfs_write()` (and any other call that should update mtime) to explicitly update the mtime on the metadata file throught the MDAL.  Then we can stat the md file before truncating and restore mtime to the correct value. For cp that would mean restoring the preserved value, and ensures that we keep mtime modifications for things like overwriting the file. One downside is that the repeated utime syscalls and the extra stat will increase the overhead of both writes and closes.

**Comment by jti-lanl** [comment]
Works correctly in 1.10
