### ISSUE TITLE
ls -li /marfs/jti/foo shows incorrect inode

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#18]
I've walked this through fuse, and fuse is returning a stat struct containing the proper inode, but maybe something else is wrong with it, such that the kernel decides to display it differently?

**Comment by brettkettering** [comment]
Any progress on finding why this is showing the wrong inode?

**Comment by jti-lanl** [comment]
I've traced it through the debugger, to the point where we are filling in the struct stat provided by fuse with what looks to me like correct info.  Then fuse reports the wrong thing.

One thing we do is cancel out the suid/sgid bits (per Gary's request that we keep these for ourselves to use).  Next time I look at this, I'll see whether leaving these alone changes anything.  Otherwise, maybe its some fuse callback we're missing.  Some web searching might help resolve this.

**Comment by brettkettering** [comment]
Admins are the ones who need to know what the inode is. For now we can get this from the GPFS mount.

It's a low priority. The users don't need to do this and we can work around it. We'll fix it if we can find out what's happening in FUSE.

**Comment by jti-lanl** [comment]
Fixed.   Mount with '-o use_ino'

Thanks to [this](http://sourceforge.net/p/fuse/mailman/message/29172157/).
