### ISSUE TITLE
Execute and pass tests using fake file trees

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#181]
Execute performance experiments with fake file trees. First, create them in /dev/shm to be used as source files to copy to Multi-Component. This makes the read a virtual no-op and determines what the write performance is. Also, read the same file setup that is on Multi-Component and write them to /dev/null. This makes the write a virtual no-op and determines what the read performance is.

**Comment by brettkettering** [comment]
Will, Chris D., and George:

I'm looking for some input here. Is this still a reasonable test to perform, or are we beyond this? If it is a reasonable test, please document the results here.

Thanks,
Brett

**Comment by wfvining** [comment]
I would still like to do a couple tests with the latest versions of everything. Hopefully this can get done some time this week, but we will need to find a time when the testbed is relatively quiet to get good performance numbers.

**Comment by brettkettering** [comment]
Let's discuss a quiet time for the testbed at tomorrow's 2pm meeting. For now, let's work on solving the 4KB nfsd requests to FUSE when reads are done on the interactive FTA and finalize testing to merge code for issue #163.

**Comment by brettkettering** [comment]
Dave B. suggested some proposed trees that we see in our production environment.

**Comment by brettkettering** [comment]
Given all the performance testing we've done, I'm going to close this issue. We have been doing some specific testing not related to this issue based on our experiences thus far. The next step is to have the Consultants use it on our large installation in ways they expect users to do.
