### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by benepo** [mar-file-system/marfs#187]
FYI, you have a typo on https://github.com/mar-file-system/marfs/blob/master/README.md

> one ore more

**Comment by cadejager** [comment]
Thanks, it has been resolved.

**Comment by benepo** [comment]
Fix verified, but it looks like the Github description for the project at https://github.com/mar-file-system/marfs still has the typo (at the top of the page).

**Comment by brettkettering** [comment]
Enough with the minor spelling anomalies.
