### ISSUE TITLE
remove obsolete static configuration

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#19]
This was training wheels, while we were moving into using PA2X for defining/parsing our config file.  We've outgrown it, and there is some clutter in source-files and Makefile.

**Comment by jti-lanl** [comment]
Don't remove this until PA2X is public.

**Comment by brettkettering** [comment]
I thought this was already removed now that we're using PA2X?

Brett

**Comment by jti-lanl** [comment]
We aren't using static-config, by default, but someone can still build to use it.

Until we make PA2X public somehow, this is the only way external users can build and run.

I saw that we had resolved to publish PA2X as part of MarFS, for the near-term, but not that it had been done.

Let me know, if this has been done.


Thanks,
Jeff

**Comment by brettkettering** [comment]
PA2X is a repository in this project. Check at the project level and you'll see two repos: marfs and PA2X. We are releasing the code under the MarFS LA-CC until we have an LA-CC specifically for PA2X (in the works).

Brett

**Comment by jti-lanl** [comment]
I see it.

Thanks,
Jeff

**Comment by jti-lanl** [comment]
Re-opened.  Our discussion answered my issue about waiting for PA2X to be published, but the static-config still needs to be removed.

**Comment by jti-lanl** [comment]
Apparently, I didn't click "reopen", with my previous comment.

**Comment by brettkettering** [comment]
This needs to be closed out for our Open Science MarFS version. AFAIK, we are using the configuration file and PA2X. Let's remove this code, or at least comment it out with a note saying why.

**Comment by brettkettering** [comment]
Right now one can build to invoke it.

**Comment by brettkettering** [comment]
Let's either comment out or delete this code. I don't want this to linger. Even though it's not strictly necessary for Open Science, if we keep putting it off it will never get done.

**Comment by jti-lanl** [comment]
Done.

From the commit log:
> Removed static-config options.  Tweak to configuration blueprint.
>
> Mostly-reconciled the remnants of lookup/encode/decode operations between
> fuse/src/marfs_base.{c,h} and common/configuration/src/marfs_configuration.{c,h}
> For now, marfs_base keeps using its variants of functions that encode/decode into
> object-IDs.
>
> While I was at it, I updated sec_type, MarFS_SecType, etc, to be named
> "enc_type", MarFS_EncryptType, etc.  I think these were always meant to be
> encryption-related, and it was confusing to see them called
> security-related, when we have another thing that is the security method.
>
> But this finally lead to the configuration-blueprint, where I also changed
> "sec_type" to "enc_type".  If you have your own configuration file that has
> derived from marfs_cctest.cfg, or marfs_odsu.cfg, it will be broken, until
> you change "sec_type" to "enc_type".  Sorry about that.
