### ISSUE TITLE
sync_ and close_data() failures are masked

### ISSUE THREAD

**Issue by wfvining** [mar-file-system/marfs#197]
MarFS can ignore `close_data` failures under certain circumstances. This only occurs if a write never fails but the sync and/or close call on object fail. Failed writes are still caught and the object will be treated as bad. With the latest MC version this situation is extremely unlikely (but has happened for one object in our tests) because write failures short-circuit the write as a whole once the `MIN_PROTECTION` threshold is exceeded. Previous versions of MC did not short-circuit, so write failures were not reported until close leading to corrupt/invalid data.

**Comment by jti-lanl** [comment]
I think this refers to bugs that were finally fixed in f838fdfd6d69, and 2033fa090b00.

**Comment by gransom** [comment]
Going through issues and noticed this one is still open.  As mentioned by Jeff, this issue has been addressed.
