### ISSUE TITLE
Where to retrieve configuration parser code?

### ISSUE THREAD

**Issue by NicolasT** [mar-file-system/marfs#20]
Hi,

While trying to build the MarFS code, I got stuck on the compilation in `common/configuration/src`, which requires `PARSE_DIR` to be defined, pointing to "the path to your install of Ron's code". If I'm not mistaken, this code isn't present in the repository, and I couldn't find it elsewhere.

Any pointers? Thanks!

**Comment by jti-lanl** [comment]
Hi Nicolas,

I've just pushed some tweaks that seem to allow our old static configuration to work again.
We've been using the newer PA2X for a while now, so the static approach hasn't been
exercised in a while, but I was able to get the static approach to build and mount, and
did some simple writes and reads.  Like I said, this approach hasn't been used in a while,
so there may well be problems with it.

Thanks for reminding us about PA2X being private.  We're on it to get that made public,
I'd guess within days.

Using the static approach, you'll have to edit the source, to set up your own static config, but it can work.
You would edit marfs/fuse/src/marfs_base_static_config.c    You'll have to look at the source,
to see what the config-fields are, but you can just adapt the example repos and namespaces there.

Then build and mount, something like this:

    cd $AWS4C;  make clean && make
    cd $MARFS/fuse/src;  make clean && make mnt STATIC_CONFIG=1

You'll have to supply that STATIC_CONFIG argument to 'make', for other things you do with the Makefile, as well.

System logs may give you (tons of) information about problems.

Thanks,
Jeff

**Comment by brettkettering** [comment]
PA2X is now a repository in this project. One should be able to get that code here and use it to build MarFS and to parse MarFS's configuration.
