### ISSUE TITLE
look at stream_close() in the case of OSF_TIMEOUT

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#27]
This is currently skipping any attempt to close the stream (see the old "signal QUIT to writefunc).  Instead we just cancel the GET request thread.  I'm thinking this could either (a) leave connections hanging open, or (b) add extra time to the reopening of a new connection.

**Comment by brettkettering** [comment]
Please determine how this should be handled and implement it in stream_close().

**Comment by brettkettering** [comment]
Jeff Inman to confirm that this is fixed.

**Comment by brettkettering** [comment]
Jeff thinks he knows what to do to clean-up this issue.

**Comment by jti-lanl** [comment]
CLOSE_WAIT is the state of a connection that has sent a FIN from one side, but not the other.

Here's what I thought would work:  After a timeout, instead of just killing (canceling) the PUT/GET thread that is interacting with libcurl, try a last-ditch effort to get the corresponding readfunc/writefunc to return something to curl.  The idea was that maybe libcurl needs a response from the callback before it will interact with the server.

That didn't work.  Testing with PUTs, I can use gdb to create an arbitrary delay in e.g. streaming_readfunc(), such that the stream_put() inside write() will fail with a timeout.  Tweaking stream_sync() so that it will cause the readfunc to return 0 was "successful" in getting the readfunc to return to curl (before the thread was cancelled), but this didn't prevent us from leaving a connection in CLOSE_WAIT.

I also tried suppressing the content-length header we've been putting onto PUT requests, suggesting the maximum amount we expected to write into an object.  That didn't help either.

Meanwhile, I just found this, in [the libcurl forums](http://curl.haxx.se/mail/tracker-2011-05/0001.html):
> The CLOSE_WAIT sockets are probably the ones that libcurl has in its 
> connection cache but that have been "closed" (a FIN was sent) by the server 
> already but not yet by libcurl. 
> They are not there "indefinitely" (and they really can't be) since the 
> connection cache has a limited size so eventually the old connections 
> should get closed. Also, for each newly created connection when searching 
> if there's an existing one, libcurl is supposed to detect and close "dead" 
> connections such as these.

That leads to several new ideas ...

**TBD**:

1.  The creation/initialization of curl handles in libaws4c may be overly ambitious.  If we create new connections all the time, it seems maybe every connection will be the first one in its cache, and (perhaps) no connections will be cleaned up.  Test this.

2. see [CURLOPT_MAXCONNECTS](http://curl.haxx.se/libcurl/c/CURLOPT_MAXCONNECTS.html)

3. Apparently, [we might be getting better performance](http://stackoverflow.com/questions/3787002/reusing-the-same-curl-handle-big-performance-increase) (or is it just reduced open overhead, which would still be nice), if we have different curl connections to different servers.  That sounds worth pursuing, but sounds like a fairly-involved refactoring.

**Comment by jti-lanl** [comment]
It seems that you can't use the same handle for multiple concurrent requests.  So, the idea of reusing a handle across threads, and setting CURLOPT_MAXCONNECTS is wrong-headed.

It looks like one common approach to that idea would be to have a so-called multi handle, pushing and popping easy-handles for individual threads, and using CURLMPOT_MAXCONNECTS.   However, that looks like it would require a significant reworking of libmarfs, and maybe libaws4c.  (**TBD**, maybe)

Instead, we could also just keep a pool of handles, never used by more than one thread at a time.  This would require added locking in open() and release(), so threads could remove/add from the pool, but that probably wouldn't be noticeable, and would let us take advantage of the performance boost from reusing handles.  Note that the pool should also store connections per destination-host, because the connections in a handle should all be to the same host (just a performance issue ?).  Each handle would have MAXCONNECTS connections, so we'd still limit the number of CLOSE_WAITS to pool_size * MAXCONNECTS (default 5).  (**TBD**)

Meanwhile, the simplest option of all is to explicitly reset the curl-handle, in stream_sync().  This works to eliminate CLOSE_WAITs that were cropping up.  And it's not just related to canceling timed-out threads.  We were accumulating CLOSE_WAITs for non-timed-out connections as well.
