### ISSUE TITLE
test #3

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#3]
Apparently, members of the Owners group for a github repository do not get email notifications for events.  So, I've added myself to the Developers group.  Do I get email notifications now?

**Comment by jti-lanl** [comment]
Nope.  Maybe that's because you still don't get notifications for events you create.  But how about when an issue is assigned to me, and I'm in a non-Owners group?

**Comment by atorrez** [comment]
Jeff, responding to issue 3.  Do you see this?

**Comment by jti-lanl** [comment]
Hi Alfred,

Yes.  Thanks.  So, I guess the key is that I don't see email for any actions that I originate, including assignments done through the github web interface.

Maybe everyone on the marfs "Developers" team is seeing all these notifications.

I will soon suggest that all bug reports start getting archived as github "Issues", so there may be a flurry of activity.

If you get tired of seeing these, you can change what notifications you'll get, by changing your settings at github.

Thanks,
Jeff
