### ISSUE TITLE
Make MarFS FUSE available to users on interactive FTAs

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#30]
We're using an unshare technique to have the GPFS metadata mount be visible to only the FUSE daemon process. We need to test and ensure that if the FUSE daemon process is killed that this does not allow other processes on the node to see the GPFS metadata mount.

Dave Bonnie and I talked about this and I wanted to assign this to him, but it appears that he has not accepted the invitation to join the MarFS project. Assigning to Chris Hoffman for now because they are in adjoining offices and work closely together.

**Comment by brettkettering** [comment]
I added this test to the MarFS_Test_Plan.docx in the Documentation folder.

**Comment by brettkettering** [comment]
If we implement marfs_statfs() and mount the FUSE daemon only on batch FTAs, re-exporting it via NFS to interactive FTAs, does this matter any more?

If not, let's close it.

**Comment by jti-lanl** [comment]
Maybe we should leave this open until #42 is closed?

**Comment by brettkettering** [comment]
Give this a try, but not a showstopper.

Kill it nicely with fusermount.

Kill it harshly with kill -9.

**Comment by brettkettering** [comment]
Check this on DST on 4/19.

**Comment by brettkettering** [comment]
Will do this test before returning it to users after the power outage today.

**Comment by thewacokid** [comment]
This is going to be down through the night thanks to outside factors, I have it on my "do before releasing to users" checklist.

**Comment by brettkettering** [comment]
Test this on CCstar.

**Comment by brettkettering** [comment]
Please do this on CCstar. If this is something we're considering because NFS needs to be fixed and might not work for us, we need to know the answer.

**Comment by brettkettering** [comment]
Chris Hoffman plans to work with you, Dave Bonnie, on the NFS export of the FUSE daemon from a batch FTA to the interactive FTA. If that works, then it won't matter what the answer to this question is because we'll use the NFS re-export mechanism.

Please plan to test the NFS re-export mechanism with Chris H. early the week of 6/13 and report the results to us.

**Comment by brettkettering** [comment]
Was: Ensure killing FUSE daemon does not expose metadata mount. Now we plan to re-export the FUSE mount from a batch FTA to the interactive FTA.

Testing with NFS3 on CCFTA testbed yielded 140 MB/s.

Testing with NFS4 on SDSU yielded 12 MB/s.

Chris H. and Jeff I. are going to get together and find the right NFS and settings to use on SDSU to make this work at an acceptable rate.

**Comment by brettkettering** [comment]
Experimentation showed that CCFTAs were working at the O( 100MB/s ) level and SDSU was working at O( 10MB/s). Chris Hoffman is working to figure out what is different and get SDSU to work at the O( 100MB/s ) level.

**Comment by brettkettering** [comment]
Further investigation into how to do this and get decent performance is leaning towards a conclusion that this is not practical using a NFS re-export.

Dave Bonnie will test killing the MarFS FUSE daemon that has been run and unshares the MarFS metadata file system so that users can't see it. He'll verify that killing the MarFS FUSE daemon does not expose the unshared MarFS metadata file system to the users.

If by Thursday, 6/23, we can't find a NFS re-export solution we'll use the MarFS FUSE running on the interactive FTAs that unshare the MarFS metadata file system.

**Comment by thewacokid** [comment]
Unshare is now working on the Perceus-booted clusters. :)

Beyond that, killing FUSE doesn't expose anything that wouldn't normally be seen (the unshare of GPFS still applies).  When FUSE dies or goes into a "bad" state the users cannot see anything more than they would when it's working normally.

**Comment by jti-lanl** [comment]
I hope it was very difficult to get fuse into a bad state, for testing.

**Comment by thewacokid** [comment]
I'll have to write up an issue for it, but I did come up with a reproducer specific to using NFS to beat on the mount with a parallel load.  It's not something I'd expect to see with user behavior, but it'll be worth tracking down in the future.

**Comment by brettkettering** [comment]
The capability to mount MarFS FUSE on the interactive FTA and unshare the MarFS metadata file system was proved on the Secure Campaign redcap FTA test node.

It still needs to be integrated into the production image so that it happens on all production interactive FTA.

**Comment by brettkettering** [comment]
This is duplicating what we're trying to accomplish with #42. Closing this one.
