### ISSUE TITLE
Implement SEMI_DIRECT access method

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#31]
This method is where the data is stored in a separate file system that allows update-in-place. Typically, the repository would be a parallel file system or other fully POSIX-compliant file system that allows for efficient editing of files and not just complete overwrites.

**Comment by brettkettering** [comment]
Same code path as DIRECT, but the data operations go to a remove PFS via IOFSL or other forwarding library. This is for Globus, HPSS, etc.

**Comment by brettkettering** [comment]
Pretty easy as it follows DIRECT mode, the only complication is someone needs to get IOFSL and play with it in parallel as the FUSE daemon and also as a lib.  I don’t know if we have someone that we can assign to this at some point when it makes sense to play with IOFSL. Since its can run as user space, one could even have someone try this on a production machine I guess, not sure about that.

**Comment by brettkettering** [comment]
If we're going to make it so that the FUSE mount uses the MarFS permission of read/write metadata, but not write data (e.g. only read data), then we don't need this so much. This allows the users to manage their tree and even copy the file off MarFS to a non-MarFS file system. They just can't do copies to or edit a MarFS file.

For now we won't implement this and not implement SEMI_DIRECT at this time.

**Comment by Brofessional** [comment]
Stale Issue cleanup
