### ISSUE TITLE
Implement PACKED file creation in PFTool

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#32]
After the Open Science MarFS version is released, we need to add the PACKED file creation capability to PFTool so that when it copies files to a repository that is an object store it creates large objects consisting of small files.

**Comment by brettkettering** [comment]
See what Alfred is doing with the post-processing script/application and find where files are gathered.

**Comment by brettkettering** [comment]
We would like to have this for Secure Campaign Storage, but it is not absolutely required. However, if we don't have it ready by 5/27/16, we will want to implement it shortly after that. Will you be able to meet the 5/27/16 deadline? If not, would help from Alfred Torrez and/or Jeff Inman help?

**Comment by cadejager** [comment]
I have starated an have a plan that I devised with Alfred. If I have any trouble I will ask for his help.

**Comment by brettkettering** [comment]
The implementation is not seg faulting now, but there are issues with files having corrupted data and restart flag set. Need to investigate using the offs parameter for each file packed into the larger object.

**Comment by brettkettering** [comment]
In today's discussion we decided that rather than the workers continually trying to pack more into a packed object, the master process would hand the worker a list of files, like it already does, that match the workload for a worker and the worker would pack those into a packed object and close it. That will be good enough to provide benefit to MarFS in creating packed objects from many small files.

**Comment by brettkettering** [comment]
Here's Gary's pseudo code.


I assume you get either an entire small file to copy or a part of a big file in your list of files or file parts to copy. This loop is meant to handle writing as many objects as it takes to process the list. As long as the list (if files are small) is 100 or more this should work fine.  Even 50 would probably get us enough savings. It does not sort the input array by size, but it could as an optimization later, although we probably don’t want to do that because we want to remain in dirent order for efficiency.
 
You have values that control packing
·         the max object size and that is less than or equal to your chunk size for big files, something you might want to check.
·         The big enough to be  in a pack by itself size
You have an updatemetadata array umdarray has name, pack number, file in pack, size, stuff like that
You have a counter of file of files in pack
You have an object offset
 
You get a list of files (input array)
 
/* process all the big enough files – this gets the big stuff out of the way to make packing more efficient later */
From n=1 to inputarray depth
  If object is suppose to be in an object by itself (its a chunk or its big enough)  
    Open put for that thing
    Copy the file/file part into that put
    Close object
    Update metadata for file/chunk
    Trash any object you need to
  End
End
/* process all small files */
Bzero umdarray and init counter of files in pack and object offset etc.
 
From n=1 to inputarray depth
  If file is not a chunk and not big enough  (wasn’t processed above)
    If input array n file size added to object offset would go over maxobject size then 
      Use umdarray entries to know what is in this pack, add up the bytes in the pack
      Open put stream based on first file in umdarray
      For all entries in umdarray copy file to put stream and footer info
      Close object
      Object offset = 0
      File of files in pack = 0
      Loop through umdarray and update all files metadata and trash any object you need to
      Bzero umdarray
    end
    Put input array n name and file of total etc in pack and object offset into umdarray 
    Incr n
  end
end
/* send last object */
Use umdarray entries to know what is in this pack, add up the bytes in the pack
Open put stream based on first file in umdarray
For all entries in umdarray copy file to put stream and footer info
Close object
Object offset = 0
File of files in pack = 0
Loop through umdarray and update all files metadata and trash any object you need to
Bzero umdarray
 
/* now you have processed all files, put them in objects, trashed anything needed, and updated metadata
So send messages to output/mother that you have done the work and you are ready for more

**Comment by cadejager** [comment]
I believe I have this functional in the branch pftool_packing_exeperiment on both marfs and pftool. I would like to do further testing before integrating it into the master however.

I also had to get rid of one of the checks that Jeff Inman had in marfs. We need to modify this check to allow packed files. It is in marfs_ops on line 2727.

It also appears that pftool is only grouping about 15 files together at a time. We might want to modify the settings in pftool to increase this.

**Comment by brettkettering** [comment]
Can COPYBUFFER be a parameter in pftool.mpi.cfg and pftool.threaded.cfg? It's unclear to me whether these only work with the pf* scripts or with pftool itself. The name of the file would imply that it works with pftool itself.

**Comment by cadejager** [comment]
COPYBUFFER cannot currently be a parameter in pftoool.cfg because it is not currently an option in pftool which those scripts call.

**Comment by brettkettering** [comment]
Does PFTool itself read the pftool.cfg file? If so, I don't understand why this can't be a parameter in the config file. If the config file only provides argument values for PFTool parameters used by the pf* scripts, then I get it. I would only say that the name of the file, "pftool.cfg" is misleading as it isn't really a configuration file for pftool at that point.

**Comment by cadejager** [comment]
You are correct. pftool.cfg is only read by the pf* scripts when convert it to options used by pftool.

**Comment by cadejager** [comment]
Packing has been merged in to the master branch so I am going to mark this as complete. If I do not hear otherwise I will delete the packing branches (not the history, just the marker).
