### ISSUE TITLE
Implement DIRECT access method

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#33]
I was not sure if this is officially supported or not. We don't need it for the Open Science MarFS release, but we'll need it afterwards. Please close this issue if it already works and a repository can be accessed using this method, and so indicated in a configuration.

**Comment by brettkettering** [comment]
There was some discussion about implementing this for zero-length files. However, we can just create an entry in the metadata file system and not create an object. We need to handle the encoding of a null object id for zero-length files in the metadata xattr.

**Comment by Brofessional** [comment]
Stale Issue cleanup
