### ISSUE TITLE
Implement "fake" marfs_statfs()

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#34]
A comment in the code says "NOTE: Until fsinfo is available, we're just ignoring".  Then we return ENOSYS.

The idea behind the comment is that once we have fsinfo maintained semi-regularly by Alfred's scripts, we can provide semi-up-to-date information about available storage, etc, in a MarFS file system.  What will be needed is to read fsinfo and extract info (if fsinfo contains detailed output as a result of the scripts), or to stat it (if fsinfo just gets truncated to size).  I believe the former is the case.  Then we fill out the statvfs struct and return.

Chris H and Dave B were speculating about exporting fuse via NFS from the interactive FTA to one of the batch FTAs.  (Or maybe going the other direction would address fears of allowing access to GPFS when fuse goes down?)  Anyhow, NFS needs staffs, for that to work.

Also , statfs is needed to support 'df', which is not necessarily something important.

**Comment by jti-lanl** [comment]
Looks like fsinfo is getting initialized as a sparse file, so we'd stat it to see the total usage (under a given mount-point).

Then we need to fill out this struct:

           struct statfs {
              long    f_type;     /* type of file system (see below) */
              long    f_bsize;    /* optimal transfer block size */
              long    f_blocks;   /* total data blocks in file system */
              long    f_bfree;    /* free blocks in fs */
              long    f_bavail;   /* free blocks avail to non-superuser */
              long    f_files;    /* total file nodes in file system */
              long    f_ffree;    /* free file nodes in fs */
              fsid_t  f_fsid;     /* file system id */
              long    f_namelen;  /* maximum length of filenames */
           };

bfree/bavail can come from the namespace.quota_space in the config.  But we allow these to be -1 for "unlimited".  What then?

files/ffree can come from namespace.quota_names in the config, or from an actual stat on the underlying mdfs (e.g. gpfs) in namespace.md_path, whichever is smaller, I guess.

I believe Alfred's tools already account for storage that is used in the trash, and don't count that as "used" storage, for quota purposes.  However, it would appear in the namespace.trash filesystem.

**Comment by brettkettering** [comment]
It was decided that the Open Science release would have this feature in the "fake" mode. That is, put information in the statfs structure that says there is free space. This will allow us to re-export the FUSE mount from the batch FTAs.

**Comment by jti-lanl** [comment]
You can now use the md_path in the root-namespace (i.e. the one that has mnt_path=/ ) to point at the root fileset in GPFS (or, in general, at the root of the MDFS) .  For instance, /gpfs/gpfs_test, on ODSU.  Then, statvfs() or df on the fuse mount will just report the statvfs of this md_path.

If you don't set md_path this way, we'll just return a bunch of faked values that make it look like we've got the maximum possible space and inodes available.
