### ISSUE TITLE
Ensure MarFS pfcp restart works

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#38]
This may be more appropriate for the PFTool project, but I thought I'd put it here to remind us that we need this capability working for MarFS.

pfcp -n will only copy files for N-N that have not succeeded already, so the N-N case is covered where we won’t have to start from the beginning in the event of a failure. If Jeff adds retries for writes that will alleviate most other failure scenarios (at least that we’ve encountered to this point in our work). That leaves a probably infrequent occurrence where N-1 does not finish copying because even write retries could not get it to work.

For Open Science it would be nice to have this work, but we can live without it.

For further releases we want restarts to work. Irrespective of file type (PACKED, UNI, MULTI), we need to have a way to clear out any partially written object and start writing over beginning with the last object that was not completed.

**Comment by jti-lanl** [comment]
For the record, N-to-1 has about the same likelihood of some of the writes failing as N-to-N does, given the same sizes of writes.  For restarting N-N, unless the files are large, pftool will just delete them and re-write them.  This was working correctly for some tests done a while ago.  For restarting N-1, we need to depend on the new pftool restart capabilities, which record which parts the file are missing, and  commissions new work on those chunks.

**Comment by brettkettering** [comment]
This is the same bug defined by issues in the PFTool repository. Getting rid of this one.
