### ISSUE TITLE
Scality recommends tcp_syncookies=0

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#40]
Ensure that this network setting is set to 0 (zero) on the ring servers for sure. We may not want to do it on the FTAs because the are somewhat "outward facing" and could open the FTAs to a SYN Flood attack. Though, if anyone on our network does that to our FTAs they're going to lose their privilege to compute here.

**Comment by cphoffma** [comment]
Set to zero for ring servers.
