### ISSUE TITLE
Set tcp_sack=1 on FTAs and Ring Servers

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#41]
This setting forces some synchronization in TCP communications. Though one might first think this would slow things down, it in fact yields much better consistent performance. It helps HTTP-based protocols avoid the switch "incast" problem.

Set the FTAs and Ring servers to use tcp_sack=1.

**Comment by cphoffma** [comment]
SACK=1 to for storage nodes and fta.next profile (will use in production).
