### ISSUE TITLE
PFTool must use username and password for sproxyd access

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#47]
Implement that PFTool must use a username and password to access Scality objects via sproxyd. The username and password will be protected such that PFTool must escalate to root to access it.

**Comment by brettkettering** [comment]
The process is understood, but not implemented.

This is really over and above with the FUSE mount being exported to interactive FTAs and not being able to login to the batch FTAs.

**Comment by brettkettering** [comment]
In Open Science we are exporting the MarFS FUSE file system from a batch FTA to the interactive FTA and the only access to this mount will be via an exported NFS (or SSHFS) mount on the interactive FTA. Consequently, username/password is not necessary as it doesn't buy any additional security. However, it will probably be required for the secure network. If the CCB determines on 1/7/16 that we still need username/password authentication for Open Science we'll implement this now, otherwise, we'll wait until we implement the secure Campaign Storage.

**Comment by cadejager** [comment]
I never heard what the CCB said. Should this be resigned to Secure Campaign Storage?

**Comment by rocr** [comment]
CCB doesn't required user/non-clear password access to the Scality ring 
for open science.

Ron

**Comment by brettkettering** [comment]
Code committed. Functionality seems to be working. Needs some more testing.

**Comment by cadejager** [comment]
After moderate testing I have not found the behavior of pftool to be affected by the code change.
