### ISSUE TITLE
Multiple repository striping

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#53]
Stripe across multiple repos via hash start and round robin ( risk mitigation for data scaling). Hash to a repository to start and then send chunks out to other repositories in a round robin fashion. Improves parallel writing and reading.

**Comment by brettkettering** [comment]
Not sure how this is different than sharding.

**Comment by thewacokid** [comment]
This is for data striping across repos.  Sharding is for metadata parallelism within a directory structure.

**Comment by Brofessional** [comment]
Multi-component has made this issue obsolete.
