### ISSUE TITLE
Backup object metadata

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#63]
List all objects in a bucket because good metadata is in the object name.

I'm not clear on what this is to do.

**Comment by jti-lanl** [comment]
This is an issue with sproxyd, where there are no "buckets", and in fact our object-IDs are not retained anywhere by Scality.
Instead (with sproxyd), our object-IDs just hash to some long string of hex digits which is the "true" name of the object.

**Comment by jti-lanl** [comment]
The plus side of sproxyd is that not retaining this info allows faster access / lower overhead.

**Comment by brettkettering** [comment]
Scality backs-up its metadata internally. 

Go ahead and implement a backup of Scality's backup files.

**Comment by cphoffma** [comment]
This is done. The backup of bizobj.bin's is handled by crond.

**Comment by rocr** [comment]
I thought Scality was working on getting a bug out of the scripts, since 
it doesn't follow symlinks..  and we use symlinks now.
