### ISSUE TITLE
Offline reconcile/repack

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#65]
This is in case trash is lost. I'm not exactly sure how losing the trash would require this. Perhaps you'd look through files with xattrs that say they're deleted and go through and delete them.

**Comment by brettkettering** [comment]
A good learning tool towards developing a parallel repacker. Reconcile (finding orphans that might be in the data store or the metadata store, but not both) can wait.

**Comment by atorrez** [comment]
Initial version completed, tested and checked in.
