### ISSUE TITLE
RAID across repositories

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#71]
Recovery and rebuild utilities are hard. This is a concept vendors are thinking about for the 2020 - 2025 time-frame. 

Doing RAID on top of already RAID'd devices is for protection against years of sitting on the repository.

First step would probably be striping over RAID devices as underlying storage.

**Comment by GiorgioRegni** [comment]
Do you mean RAID or a form of erasure coding on the network?

**Comment by brettkettering** [comment]
We mean implementing RAID over several object or file system repositories. The underlying object or file system repositories can be using erasure coding or RAID themselves. This is RAID on top of that. So, it's as if each object or file system repository is a HDD in traditional RAID. Let's say we had a total of 10 such repositories, we could implement RAID6 using 8+2, for example. I'm sure Gary Grider could go into much more detail of you're interested in that level of detail.

**Comment by Brofessional** [comment]
Stale issue cleanup
