### ISSUE TITLE
marfs_release() should skip writing recovery-info if obj-stream wasn't actually opened

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#75]
For instance, this is an attempt to truncate a file (moving it to the trash), which failed to gain access to the trash (different problem I'm trying to deal with).  But marfs_release() still tries to write recovery-info, even though the object-stream was never opened (?)

[Marked as low-priority because it doesn't actually hurt anything, or prevent correct operation.]

[foo.txt](https://github.com/mar-file-system/marfs/files/79906/foo.txt)

**Comment by jti-lanl** [comment]
Maybe I was wrong about what's going on here.  I assumed that open never opened a stream.  Here's a more-complete log snippet, including the open.

Maybe it's trying to PUT to an object that already exists?  But that would be causing problems for all truncates.  Must be more to it.

[foo.txt](https://github.com/mar-file-system/marfs/files/79923/foo.txt)

**Comment by brettkettering** [comment]
Needs deeper diagnosis to determine if it's causing a problem that will be an issue for the Secure Campaign release.

**Comment by brettkettering** [comment]
Applies to zero-length files. Not pressing, but trying to reproduce it. Let's fix this if we can, but it will be lower priority than other tasks for Secure Campaign. We can live without it in Secure Campaign.

**Comment by jti-lanl** [comment]
Even contriving a misconfigured trash-dir (where user does not have write access) does not currently produce the bad Scality interaction shown in the original.  Now, you just get a "mysterious" permission denied error, resulting from the MDFS trash-access error.  However, it was also truncating the original, and writing recovery-info.

**Fixed**, by moving the stream_abort() to earlier in ftruncate(), which causes a flag to get set in the ObjectStream.  Then, we can test that flag in release() and skip out before doing damage.

Weird/Frustrating:  we use access() to determine whether an open() will succeed.  But, in some cases, "access(mdfs_path, W_OK)" returns zero, while "open(mdfs_path, O_WRONLY)" fails with EACCES.

**Discovered a new problem** (somewhat similar, but more important) when trying to overwrite a file to which you don't have access.  I'll create a separate issue.
