### ISSUE TITLE
NFS not like FUSE, when overwriting existing files

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#76]
When writing an existing file, FUSE calls open(), followed by ftruncate().  The ftruncate() is where we move the original file to the trash, transfer xattrs, truncate the MDFS file, etc.

But, when the FUSE mount is exported via NFS, a user that overwrites a file seen on the NFS mount just generates the open() call to the underlying FUSE client, but no ftruncate().

Among other bad things:

(1) This causes us to attempt to write to the same object-ID for the new writer, which results in a 500 'Internal Server Error' at close time.

(2) For some reason, this also results in a bad write (non-contiguous offset), which returns EINVAL to the user.

… [marfs_ops.c:2250]       marfs_write           | #ERR non-contig write: offset 130976, after 0 (+ 0)

**Comment by brettkettering** [comment]
Any clues as to why FUSE only calls open() when this happens on a NFS mount of FUSE? What happens if you use SSHFS instead of NFS?

**Comment by jti-lanl** [comment]
There may be a fairly simple solution:  If open sees a non-zero-sized file, with an object-type other than Nto1, then it could just call ftruncate() itself.

I think that might work.

**Comment by jti-lanl** [comment]
That works (as far as it goes) for overwriting existing files.

However, we've discovered that NFS has a lot of other expectations that we can't currently handle.  For example:

* NFS server threads issue writes to discontiguous offsets.  (They assume we support sparse files.)  We could buffer these, if we wanted to go to the trouble.  Using a single server thread eliminates the problem, but would also make the server horribly ineffective, for more than one client.

* NFS server issues open / fsync / close, while another fd is taking writes to the same file.  Apparently, NFS makes the unreasonable assumption that we can correlate this second open with an existing fd.

* NFS threads make frequent calls to stat (getattr).  However, we don't necessarily update the MDFS (which would support those stat-calls) until close.  Will it start making assumptions that something is going wrong, when all of its writes and syncs are not changing the file-size?

We're punting in favor of sshfs, for now.
