### ISSUE TITLE
problems setting uid/gid per-thread

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#77]
I think [interrupts compromising thread-safety during seteuid operations] is the best remaining explanation for what is going on in logs like the included one.  (Line numbers were added.)  I think the way this is provoked is to do a tab-complete while creating the command-line (which does a opendir/readdir/closedir), then run the command (which does a write).  The release_dir then might happen at the same time as the write.  This is all happening over an NFS export of the marfs FUSE mount.

Just look at the push_user/pop_user calls.  Lines 3,4 and 24,25 show the normal push-pop behavior.  

Then there's a weird scramble.  Log lines aren't necessarily an exact reflection of the real order of events, but this appears meaningful.  Line 30 is in the middle of push_user, having pushed the egid, and stored 0 (the root euid) for later recovery.  But this is interrupted (I presume) by a call to fuse_release, which calls push_user again, called as root, at line 34.  It must be called as root, because the destination gid is 0, which would have come from the fuse context.  This may be on behalf of the NFS mount (mounted as root on the client).

The push euid at line 35 must be for the getattr (because it is pushing a user ID, not uid 0).  Then the seteuid at line 36 is on behalf of root.

So, I think lines 30 and 35 go together, then the interrupt, then lines 31-36 (minus 35).

If these were just different threads writing to the log, then the values being stored for later recovery would be in different per-thread spots, so there should be no interference.  Each thread would restore its own defaults in pop_user().  But the pop_user calls are screwed up now, I think, having mixed up data.

At line 88, push_user is now escalating from 493 to root.  I put a question-mark on whether this is actually "escalation" or not, because I think this is actually the opposite -- the thread was running with euid 493 when root calls, at which point it is able to set euid to 0 on behalf of root.

I've gone to extremes to make push and pop thread-safe, so I'm thinking this has to be the same thread handling one push_user, while in the middle of handling another one, which sounds like an interrupt.

This is awkward to engineer in the debugger.  Maybe a better approach is to add some log details, to show the thread ID and addresses of storage.  If it is indeed the same thread, then we can go to locking, or something.

Maybe this only happens when NFS is exported on top of fuse?  We do not start fuse with '-o intr'.

[foo.txt](https://github.com/mar-file-system/marfs/files/80425/foo.txt)

**Comment by jti-lanl** [comment]
My suggestion for how this is caused is wrong.  It's not releasedir, it's just release.  that happens when the write is closing.  This thing is thus very reproducible.

**Comment by brettkettering** [comment]
FUSE normally runs as root, right? It seems like the change from 493 to 0 is a pop_user thing. But for some reason when this push_user call happened the active uid was 493.

Is this a showstopper for Open Science?

**Comment by jti-lanl** [comment]
It leads to a stuck situation where everything the user does fails, because push_user is failing to set egid, because the thread still has a user euid.

(I set egid first, because it seemed there were problems doing things in the other order.)

I'm open to suggestions / education.

**Comment by johnbent** [comment]
Perhaps at line 172 in https://github.com/mar-file-system/marfs/blob/master/fuse/src/main.c, the call to *saved_egid = getegid(); is not thread-safe.  So if you get it after someone else has temporarily set it, then you get the wrong value and subsequently restore it.  You may need a mutex or something.  Hmm, that actually shouldn't be the case since getegid() is supposed to be different for each thread so one thread calling setegid() shouldn't screw up another thread calling getegid().  It could only be screwed up if the same thread was interrupted by a signal handler or something which seems unlikely.  In any case, if you add process and thread ids to your nice foo.txt log file, that might help debug this as well.

Generally, I wonder also if you shouldn't call getpwuid() instead of getegid()?  getpwuid() won't be influenced by calls to setegid() so it should be safer.

It's not super straightforward but you might try reading the comment at line 698 in the corresponding PLFS code: https://github.com/plfs/plfs-core/blob/master/fuse/plfs_fuse.cpp.  I *think* it's related and I *think* that function basically implements correctly what you need here.  Although I have to admit I'm generally confused by this so this might all be wrong...

**Comment by jti-lanl** [comment]
I thought it would be thread-safe in the current implementation, in which saved_egid and saved_euid both come from per-thread storage allocated via pthread_key_create() and friends.

I only went to the bizarre extent of using pthread primitives to allocate per-thread storage because I was running into (something like) this same problem when I was using local variables, and assumed ... well, it was dumb.  As we discussed, you'd expect local variables to live on the stack and also be thread-safe.

So, that makes me think this really is thread-safe, which implies that it must be the same thread that is handling the two different calls that appear mixed together in the log. That's why I figured this must be some kind of interrupt thing.  I could still be wrong about all this.  I'm setting up some tests printing thread-IDs into the log.

Thanks for the link, and the discussion.  The comment you referred to seems to suggest the same thing I was starting to suspect, which is that I might need locking.  I assumed that if I needed locking I was doing it wrong.   Dang it.  But it looks like PLFS fuse had to do it, too.

Thanks.

**Comment by jti-lanl** [comment]
Okay, some insight.  The thread-safety is fine.  And there is no interrupt.  It really is two different threads running at the same time.

Here's the joke:  when any thread calls seteuid(), it affects the entire process!   Therefore, whoever calls it last wins.   [... sound of palm striking forehead]

There's another thing called setfsuid() that looks like maybe what we want.   (Hmm.  "set file-system uid".   Curious.)

This page refers to some issues with access() and quota(), but it dates back to 2009.  They also mention some ugliness with capabilities.

    http://stackoverflow.com/questions/1223600/change-uid-gid-only-of-one-thread-in-linux

**Comment by jti-lanl** [comment]
Issue #79 describes an apparent bug in setfsgid().

It also suggests using 'syscall(SYS_seteuid)' instead of 'seteuid()' to get per-thread seteuid behavior.  I'm closing this issue, because the remaining questions are now covered in #79.
