### ISSUE TITLE
Batch scripts implement username/password for object store access

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#80]
Use the same username/password mechanism that MarFS FUSE and PFTool use to access the object store in an authenticated manner for the scripts that access the object store.

**Comment by jti-lanl** [comment]
Code is ready for testing.  Pending some repairs on ODSU.

**Comment by jti-lanl** [comment]
You'll need to update aws4c, as well as marfs.

/root/.awsAuth  contains the user/password  which is snarfed up by root at initialization-time.  I believe libaws4c enforces that it is chmod 700.

I updated marfs/common/configuration/src/marfs_odsu.cfg to refer to the new proxies.  For the one requiring user/pass, you give security_method = HTTP_DIGEST.

We only have one driver-alias (bparc), so we can only have one namespace.  I had it refer to the authenticating proxy.

Our new proxies ("proxy1", "proxy2") don't match the name of the old proxy ("proxy"), so all the old obj-IDs have wrong URLs in them.  Effectively we have new repositories.  Thus, your old files will appear unreadable. However, you can retrofit them using marfs/fuse/scripts/retrofit_odsu_file, something like this:

`for F in $(find /gpfs/gpfs_test/atorrez/mdfs/jti -type f); do echo $F; ../scripts/retrofit_odsu_file $F 1; done`

In my case, this retrofitted ~20k files in a minute or two.  I can read them from the authenticating proxy now.

Things work over sshfs, as root.  I haven't tried other users yet.  I can create some of these, if it's okay with you-all, or someone else can do it, if you'd prefer.

I dug through the traffic from odsu-master to Scality, for a small write, and I can confirm that the password doesn't appear in clear-text, though, as expected, the data-contents are not encrypted, and the user-name appears in clear-text.

**Comment by jti-lanl** [comment]
Re-opening.  #46 is the one I meant to close.  The comments above relate to user/pass with FUSE.

**Comment by jti-lanl** [comment]
I believe any batch-scripts that use libmarfs, pftool, or fuse, to do their object interactions will "just work".

**Comment by brettkettering** [comment]
Let's have Alfred test that hypothesis.

Thanks,
Brett

**Comment by atorrez** [comment]
With Jeff's help, found I needed to modify code to call s3_http_digest(1) prior to update_pre call.
Jeff also recommended adding access method checks as well. These were implemented in a function.

Garbage collection now working.

if (pre->repo->security_method == SECURITYMETHOD_HTTP_DIGEST)
      s3_http_digest(1);

   if (pre->repo->access_method == ACCESSMETHOD_S3_EMC) {
      s3_enable_EMC_extensions(1);

      // For now if we're using HTTPS, I'm just assuming that it is without
      // validating the SSL certificate (curl's -k or --insecure flags). If
      // we ever get a validated certificate, we will want to put a flag
      // into the MarFS_Repo struct that says it's validated or not.
      if (pre->repo->ssl ) {
         s3_https( 1 );
         s3_https_insecure( 1 );
       }
   }
   else if (pre->repo->access_method == ACCESSMETHOD_SPROXYD) {
      s3_enable_Scality_extensions(1);
      s3_sproxyd(1);

      // For now if we're using HTTPS, I'm just assuming that it is without
      // validating the SSL certificate (curl's -k or --insecure flags). If
      // we ever get a validated certificate, we will want to put a flag
      // into the MarFS_Repo struct that says it's validated or not.
      if (pre->repo->ssl ) {
         s3_https( 1 );
         s3_https_insecure( 1 );
      }
   }

**Comment by atorrez** [comment]
Added code per previous update and tested successfully.
