### ISSUE TITLE
marfs_restart xattr should include MDFS trash pathname

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#85]
The restart xattr only exists while the file is opened for writing.  Thus, if something goes wrong during the write, the restart xattr is an indicator that the file is incomplete.

When such a file is moved to the trash (e.g. the incomplete original is overwritten, or is simply deleted), then the GC script doesn't have the usual extended POST xattr, to give it the path to the file in the trash for deletion.  So, we should include that path in the restart xattr (?  or maybe add a POST xattr?  or something), so the GC script will have an alternative way to find incomplete files for deletion.

NOTE: we might reasonably forego having the ".path" companion-file, corresponding to incomplete (restart) files in the trash, because who's going to undelete an incomplete file?  On the other hand, what if the incomplete file is gigantic, and only partially-written N:1 via pftool?  But, in that case, why was it deleted?  Do you really want to undelete an older version of a partially-written file?  Probably not.

**Comment by jti-lanl** [comment]
Problem:  How do we avoid trashing files that are currently open for writes?

**Comment by brettkettering** [comment]
Need to do this in order to get rid of trashed files that were imperfectly written. If we don't get this done, then these files will accumulate in trash and we won't return the available storage to the users.

**Comment by brettkettering** [comment]
Time for implementation.

**Comment by jti-lanl** [comment]
UPDATE:

We now always add the POST xattr to files going to the trash, so GC can always find the pathname of the file in the trash from POST.  Incomplete Uni files are deleted immediately, instead of going to the trash.

REGARDING GC OF OBJECTS FOR INCOMPLETE FILES:

You can't normally write an "incomplete" N:1 file from fuse.  If you interrupt (ctl-C) a 'dd' or 'cp' from a large source-file, you just end up with a smaller (complete) N:1 destination-file than you intended.   It will have a normal POST xattr showing the number of objects actually written.  Deleting such a file will add the MDFS path to POST, in the normal way, and GC can just proceed normally.

Incomplete Uni files created from fuse would not have PRE, and would be deleted directly by the trashing functions, instead of going into the trash.

However, if fuse crashes before closing a Multi file, we previously just had RESTART, which was not enough info to allow reclaiming of chunk objects.  Fuse now installs PRE (aka OBJID) at the first moment when there are completed objects associated with the file.  This is at close-time for Uni, and at the time of finishing the first chunk, for a Multi.  If fuse crashed before finishing such a Multi, the file would not yet have a POST with the chunk-count, etc.  If such a file is moved to the trash, we will generate a POST, showing the MDFS path, with correct post.chunks, and post.chunk_info_bytes.

From pftool, an incomplete file will have RESTART (and PRE), as well as a POST xattr showing more objects than were actually written.  If such a file is trashed, the POST xattr will again have its MDFS path updated, so GC could find it in the usual way.


so GC must do the following:

* if a file in trash is complete (doesn't have RESTART) and has post.obj_type=Multi, then just iterate for post.chunks, generating chunk object-IDs, and deleting those objects.  Then use post.mdfs to find the trash path, and generate the *.path companion pathname, and delete those two files.

* If a file in the trash has RESTART and (pre.obj_type==OBJ_FUSE), then it's a Multi file created from fuse, and fuse crashed before closing.  This of course never actually happens, but, if it did, the trashing procedure will have generated a POST, with correct post.chunks and post.chunk_info_bytes.  Handle it like a completed Multi-file (see above).

* If a file in the trash has RESTART and (pre.obj_type==OBJ_Nto1), then it's an incomplete Multi file created from pftool.  Use read_chunkinfo() to crawl chunks, but some of them may be empty.  These can be identified by having config_vers_maj == 0.  For non-empty chunks, generate object-IDs and delete.  There should be at most post.chunks of them, but almost-certainly less than that.

There's an example of how to use read_chunkinfo() in the new file **fuse/src/demo_read_chunkinfo.c**.  You can just cd there and 'make demo_read_chunkinfo', then invoke it on some MD file.
