### ISSUE TITLE
Separate file set for trash

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#91]
2/2/16's meeting decided to have a separate file set for trash. This would imply that we need a couple things done:

1) System Administration needs to create the file set in GPFS. Chris Hoffman or Dave Bonnie?

2) Scripts need to implement the use of the separate file set. Alfred Torrez

**Comment by atorrez** [comment]
Discussed with admins.  Fileset will be created and utilities currently scans all filesets including trash.
