### ISSUE TITLE
Enable authentication on MarFS testbed

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#92]
Work with Ron C. to get this functionality configured on the MarFS testbed so that we can test there and on the Open Science system.

**Comment by brettkettering** [comment]
HB: Have you and/or Ron worked on this? If not, when do you plan to get this working?

**Comment by hbchen** [comment]
Ron can get on to my Scality test bed and enable AUTH.

This is the current plan.

I will check with Ron on this ticket.


HB




________________________________

**Comment by brettkettering** [comment]
Moving assignment to Ron.

**Comment by brettkettering** [comment]
here is how to set up AUTH_DIGEST for an apache server with Scality for
all processes running on their standard ports. Do these for steps on all
storage servers.


[1]:  Make sure the ring is up and working.

[2]:  Put this below (not including the asterisks intO;
     /etc/httpd/conf.d

***
Listen 81

<VirtualHost *:81>
DocumentRoot /var/www
# [f] is used to avoid errors when some files are not installed
Include conf.d/_scality/sproxyd.conf (and replace DATA-1 with the name
of the ring.

#
# mod_auth_digest authentication for Scality
#
<Directory "/var/www">
   AuthType Digest
   AuthName "DATA-1"
   AuthDigestAlgorithm MD5
   AuthDigestDomain http://localhost/proxy*
   AuthDigestNcCheck Off
   AuthDigestNonceLifetime 0
   AuthDigestQop auth
   AuthDigestProvider file
   AuthUserFile /etc/httpd/.htpasswd-digest
   AuthGroupFile /dev/null
   Require valid-user
</Directory>

</VirtualHost>


Listen 127.0.0.1:82

<VirtualHost 127.0.0.1:82>
DocumentRoot /var/w3
# [f] is used to avoid errors when some files are not installed
Include conf.d/_scality/srebuildd.con[f]
</VirtualHost>
***

[3]:  use htdigest to create a password file:
# htdigest
Usage: htdigest [-c] passwordfile realm username
The -c flag creates a new file.

where realm is the name of your ring.

[4]: copy the passsword file to: /etc/httpd/.htpasswd-digest (when using
the config file above.

this is what I used on a default installation.

**Comment by brettkettering** [comment]
htdigest creates a bunch of hex digits, which are I guess an encrypted version of the password I typed.
Is there a way to get it to generate a human-friendly password?
Can I just put any text I want into the password part of /etc/httpd/.htpasswd-digest

Also, when you allowed with/without http-digest, did you just do that by leaving the "Listen 80" in the httpd.conf?

**Comment by brettkettering** [comment]
you should use the -c option, that would create a file (you
actually need that file on the server anyway)

htdigest -c .htpasswd-digest DATA-MARFS-1 rocr   would create that file.

contents of that file:
rocr:DATA-MARFS-1:85886d4ee411b04a7ce02313c86e99ec


That file goes on the server, for apache to use (I stuck it in
/etc/httpd, that way it is out of the document tree).

You should not have to do anything with the MD-5 hash itself (it's not
encrypted, it's a one way MD-5 hash).

When you use the password you used with htdigest, in your application,
  curl will hash your password and sends it to Apache auth_digest.

So if you use a "human friendly" password with htdigest, for example:


]# htdigest -c .htpasswd-digest DATA-MARFS-1 rocr
Adding password for rocr in realm DATA-MARFS-1.
#New password:
and you type:

  'humanfriendly'

#Re-type new password:

and you type again:

  'humanfriendly'


your password will be:  'humanfriendly' (and not the hash)


using the hash as your password will not work,  since lib curl will hash
the hash again, instead of 'humanfriendly' and the server thinks the
ghash is your password instead of your password.

In your curl application you'd use 'userfriendly' as your password.

for example, the linux curl command I'd have to use as follows:

#curl --digest -u rocr http://sdsu-sn001:81/proxy/bparc/hosts-test-0001
#Enter host password for user 'rocr':

and I would type:

'humanfriendly'    (without the quotes.)

**Comment by brettkettering** [comment]
This is done.
