### ISSUE TITLE
Refuse a MarFS metadata or data file system as source or destination

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#94]
We already have MarFS metadata file systems.

Once we have SEMI_DIRECT and DIRECT we'll have to MarFS data file systems too (not just URLs to object stores).

When a PFTool command is executed, if MarFS is configured, check the configuration file and make sure that the source and/or destination file systems are not a MarFS metadata or data file system.

We cannot allow people to copy, or otherwise affect, files on MarFS metadata or data file system. That would potentially corrupt MarFS.

**Comment by brettkettering** [comment]
There is a tool called marfs_config that is built in marfs/common/configuration/src that makes it easy for scripts to read the configuration file and determine such things as if a path is into a MarFS implementation file system. Talk to Jeff.

**Comment by brettkettering** [comment]
Time for implementation.

**Comment by brettkettering** [comment]
Do this inside PFTool itself, versus in the Python scripts, pf*.

**Comment by brettkettering** [comment]
We discussed many things that may cause this to degrade at open time, such as many different MDS file systems or thousands of files specified in a wildcard. Jeff had some ideas to take the first cut at this.

**Comment by brettkettering** [comment]
In today's discussion with Gary it was suggested that we add a configuration parameter that is something like "PROTECTED_ROOT" and we won't allow any file/directory specification to contain that. For example, the admins could define PROTECTED_ROOT to be, "/marfs/admin" and they would mount all metadata and data file systems under that. We would not allow anything with "/marfs/admin" at the start to be a source or target of a PFTool command. If the admins do mount something outside that, then they've shot themselves in the foot. This makes it efficient to check for users trying to get at MarFS implementation-specific file systems.

**Comment by brettkettering** [comment]
Further discussion today decided that we'll only check the destination to see if it is in the PROTECTED_ROOT. There is nothing to be learned by copying files out of the PROTECTED_ROOT to a non-PROTECTED_ROOT destination. Our concern is to prevent files from being copied into the PROTECTED_ROOT and corrupting the MarFS metadata.

**Comment by brettkettering** [comment]
As I recall, the latest on this was only to check the destination for something in PROTECTED_ROOT. The source doesn't matter because no xattrs are copied so no one can see the private xattrs that belong to MarFS.

**Comment by brettkettering** [comment]
Jeff Inman had implemented a fix to provide this functionality and done testing. This capability is being integrated into the MarFS tagged release for use in Secure Campaign. I'll call this closed.

Jeff can reopen if he finds an issue or disagrees.

**Comment by jti-lanl** [comment]
Just confirming for Brett:   configuration now includes a top-level key called "mdfs_top".  We forbid paths under the directory given as the configured value to be used in `marfs_opendir`, or `marfs_open` [for writes], or, for that matter, in `marfs_symlink` (because why would anyone need to do that?).
