### ISSUE TITLE
quota tool should count inodes for files that lack xattrs in marfs file-sets

### ISSUE THREAD

**Issue by jti-lanl** [mar-file-system/marfs#97]
See comment (3b) in issue #83.

Without this, a malicious (or accident-prone) user could create unlimited inodes in a DIRECT repo.

**Comment by jti-lanl** [comment]
If there's not going to be any DIRECT/SEMI_DIRECT support expected for the Secure Campaign milestone, then this issue could be differed to some other milestone.  It's potentially related to #111, if we decide that zero-length files should have no xattrs (but I hope we don't decide that).

**Comment by brettkettering** [comment]
Let's try to do this one, but consider it lower priority for Alfred than #102.

**Comment by atorrez** [comment]
Integrated and checked in.
